#!/usr/bin/env python3
"""Generate PDF guides for Understand by Geniux"""
from fpdf import FPDF
import os

os.makedirs("/tmp/super-ai-platform/downloads", exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica','B',16)
        self.set_text_color(108,99,255)
        self.cell(0,10,'Understand by Geniux',new_x='LMARGIN',new_y='NEXT',align='C')
        self.set_draw_color(108,99,255)
        self.line(10,20,200,20)
        self.ln(10)
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica','I',8)
        self.set_text_color(128,128,128)
        self.cell(0,10,f'Page {self.page_no()}/{{nb}}  |  Powered by Lazaro Intelligence  |  Dar es Salaam, Tanzania',align='C')
    def ct(self,title):
        self.set_font('Helvetica','B',14)
        self.set_text_color(255,101,132)
        self.cell(0,10,title,new_x='LMARGIN',new_y='NEXT')
        self.ln(4)
    def cb(self,body):
        self.set_font('Helvetica','',11)
        self.set_text_color(50,50,50)
        self.multi_cell(0,7,body)
        self.ln(4)
    def bl(self,text):
        self.set_font('Helvetica','',11)
        self.set_text_color(50,50,50)
        self.cell(10)
        self.cell(0,7,f'  - {text}',new_x='LMARGIN',new_y='NEXT')

# PDF 1: AI Basics
p=PDF();p.alias_nb_pages();p.add_page()
p.ct('AI Basics - Msingi wa AI')
p.cb('AI (Artificial Intelligence) ni teknolojia inayoruhusu kompyuta kufanya kazi ambazo kawaida zinahitaji akili wa binadamu.')
p.ct('Nini ni AI?')
p.cb('AI ni uwezo wa kompyuta kuiga akili wa binadamu - kujifunza, kufanya maamuzi, kutatua matatizo, na kuelewa lugha.')
p.ct('Aina za AI')
p.bl('Narrow AI - AI maalum kwa kazi moja (kama ChatGPT, Siri)')
p.bl('General AI - AI yenye akili sawa na binadamu (haijapatikana bado)')
p.bl('Super AI - AI iliyo juu ya akili wa binadamu (ya ndoto)')
p.ct('Machine Learning vs Deep Learning')
p.bl('Machine Learning - AI inajifunza kutoka data')
p.bl('Deep Learning - ML yenye neural networks kubwa')
p.bl('Generative AI - AI inayotengeneza maudhui mapya')
p.ct('AI kwa Kiswahili')
p.bl('Sartify - AI ya Kiswahili iliyotengenezwa Tanzania')
p.bl('Suno AI - Inasoma lyrics za Kiswahili')
p.bl('ChatGPT - Inaweza kujibu kwa Kiswahili')
p.output('/tmp/super-ai-platform/downloads/ai-basics.pdf')

# PDF 2: AI Tools
p=PDF();p.alias_nb_pages();p.add_page()
p.ct('AI Tools - Zana za AI')
p.ct('Nyimbo & Muziki')
p.bl('Suno AI (suno.ai) - Nyimbo kamili kwa maandishi [BURE]')
p.bl('AIVA (aiva.ai) - Muziki wa classical/cinematic [BURE]')
p.bl('Soundraw (soundraw.io) - Muziki wa background [FREEMIUM]')
p.bl('Mubert (mubert.com) - Muziki wa AI [FREEMIUM]')
p.ct('Video Generation')
p.bl('Pika Labs (pika.art) - Text-to-video [BURE]')
p.bl('Runway ML (runwayml.com) - Advanced video AI [FREEMIUM]')
p.bl('CapCut (capcut.com) - Video editing na AI [BURE]')
p.ct('Picha & Design')
p.bl('Leonardo AI (leonardo.ai) - Picha za AI [BURE]')
p.bl('Canva (canva.com) - Design na AI [FREEMIUM]')
p.bl('Remove.bg - Ondoa background [BURE]')
p.ct('Chat & Writing')
p.bl('ChatGPT (chatgpt.com) - AI chat [BURE]')
p.bl('Claude (claude.ai) - AI assistant [BURE]')
p.bl('Perplexity (perplexity.ai) - AI search [BURE]')
p.output('/tmp/super-ai-platform/downloads/ai-tools.pdf')

# PDF 3: AI Business
p=PDF();p.alias_nb_pages();p.add_page()
p.ct('AI Business Ideas 2026')
p.ct('Mawazo ya Biashara ya AI')
p.bl('1. AI Content Creation - Tengeneza maudhui kwa wengine')
p.bl('2. AI Music Production - Tengeneza nyimbo kwa wateja')
p.bl('3. AI Video Production - Tengeneza video kwa biashara')
p.bl('4. AI Tutoring - Fundisha AI kwa wengine')
p.bl('5. AI Consulting - Saidia biashara kutumia AI')
p.bl('6. AI Chatbot Development - Tengeneza bots kwa biashara')
p.bl('7. AI Translation - Tafsiri kwa AI')
p.bl('8. AI Social Medicine Management - Simamia social media')
p.ct('Jinsi ya Kuanza')
p.bl('Chagua niche moja')
p.bl('Jifunze zana za AI zinazohitajika')
p.bl('Tengeneza portfolio ya kazi zako')
p.bl('Anza kutoa huduma kwa bei nafusi')
p.bl('Ongeza bei unapopata uzoefu')
p.output('/tmp/super-ai-platform/downloads/ai-business.pdf')

# PDF 4: AI Ethics
p=PDF();p.alias_nb_pages();p.add_page()
p.ct('AI Ethics - Maadili ya AI')
p.ct('Masuala Muhimu')
p.bl('Privacy - AI inaweza kukusanya data yako')
p.bl('Bias - AI inaweza kuwa na ubaguzi')
p.bl('Job Loss - AI inaweza kuchukua kazi za watu')
p.bl('Misinformation - AI inaweza kutengeneza uongo')
p.ct('Jinsi ya Kulinda Nafsi')
p.bl('Usiweke data nyeti kwenye AI')
p.bl('Hakikisha taarifa kutoka AI')
p.bl('Tumia AI kwa njia ya maadili')
p.bl('Jifunze kila siku kuhusu AI')
p.ct('Mustakabali wa AI')
p.bl('AGI (General AI) - inakuja lakini sio karibu')
p.bl('AI itabadilisha kazi nyingi')
p.bl('Wataalamu wa AI watakuwa na kazi nyingi')
p.output('/tmp/super-ai-platform/downloads/ai-ethics.pdf')

# PDF 5: Complete Guide
p=PDF();p.alias_nb_pages();p.add_page()
p.ct('Understand by Geniux - Complete Guide')
p.cb('Hii ni mwongozo kamili wa kujifunza AI kwa Kiswahili. Unapata video za tutorial, PDF guides, na vifaa vya kushushwa.')
p.ct('Yaliyomo')
p.bl('Module 1: Msingi wa AI (3 masomo)')
p.bl('Module 2: AI Tools (5 masomo)')
p.bl('Module 3: AI Updates (3 masomo)')
p.bl('Module 4: Vitendaji vya AI (4 masomo)')
p.bl('Module 5: AI Ethics & Future (2 masomo)')
p.ct('Mawasiliano')
p.bl('WhatsApp: 0657 323 904')
p.bl('Email: lazarojohnie54@gmail.com')
p.bl('Telegram: @Cybergeniuxbot')
p.bl('GitHub: lazarojohnie54-a11y')
p.output('/tmp/super-ai-platform/downloads/complete-guide.pdf')

print("All PDFs generated!")
for f in os.listdir('/tmp/super-ai-platform/downloads'):
    sz=os.path.getsize(f'/tmp/super-ai-platform/downloads/{f}')
    print(f"  {f} ({sz/1024:.1f} KB)")